version: '3.8'

# Services
services:
    # Go Service
    go:
        build:
            dockerfile: ./deployment/local/go/go.dockerfile
        container_name: sacosbe-go
        stdin_open: true
        tty: true
        volumes:
            # - './app:/app'
            - './app:/app'
        ports:
            - 9000:9000
        networks: 
            - backend    
    # Nginx Service
    nginx:
        build: 
            dockerfile: ./deployment/local/nginx/nginx.dockerfile
        container_name: sacosbe-nginx
        ports:
            - 8484:80
        links:
            - 'go'
        volumes:
            - './deployment/local/nginx/conf.d:/etc/nginx/conf.d'
            - './logs/nginx/:/var/log/nginx'
        networks: 
            - backend        
        depends_on:
            - go
    mariadb:
        build:
            dockerfile: ./deployment/local/mariadb/mariadb.dockerfile
        container_name: sacosbe-mariadb
        restart: always
        stdin_open: true
        tty: true
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: sacos
            MYSQL_PASSWORD: sacos
            MYSQL_DATABASE: sacos
        ports:
            - 3367:3306
        volumes:
            - ./database/mariadb/data:/var/lib/mysql
        networks: 
            - backend

networks:
    backend:
        driver: bridge   
         

    


